#!/usr/bin/env bash
# Patches the Gradle config generated by `flutter create .` so the release
# APK builds on modern Flutter, where some transitive plugins (e.g.
# flutter_plugin_android_lifecycle) require compiling against Android API 36.
set -euo pipefail

APP_KTS="android/app/build.gradle.kts"
APP_GROOVY="android/app/build.gradle"
ROOT_KTS="android/build.gradle.kts"
ROOT_GROOVY="android/build.gradle"

# Bump the app module's compileSdk
if [ -f "$APP_KTS" ]; then
  sed -i 's/compileSdk = flutter.compileSdkVersion/compileSdk = 36/' "$APP_KTS" || true
fi
if [ -f "$APP_GROOVY" ]; then
  sed -i 's/compileSdk flutter.compileSdkVersion/compileSdk 36/' "$APP_GROOVY" || true
fi

# Force every subproject (incl. plugins) to compileSdk 36
if [ -f "$ROOT_KTS" ]; then
  cat >> "$ROOT_KTS" <<'EOF'

subprojects {
    afterEvaluate {
        val androidExtension = extensions.findByName("android")
        if (androidExtension is com.android.build.gradle.BaseExtension) {
            androidExtension.compileSdkVersion(36)
        }
    }
}
EOF
  echo "Appended subprojects override to $ROOT_KTS"
elif [ -f "$ROOT_GROOVY" ]; then
  cat >> "$ROOT_GROOVY" <<'EOF'

subprojects {
    afterEvaluate { proj ->
        if (proj.hasProperty('android')) {
            proj.android {
                compileSdkVersion 36
            }
        }
    }
}
EOF
  echo "Appended subprojects override to $ROOT_GROOVY"
fi

echo "Android SDK patch complete."
